services:
  db: #Serviço do banco de dados
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment: #Variáveis de ambiente
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck: #Verifica se o banco de dados está online
      test: ["CMD-SHELL", "pg_isready -U postgres"] #Comando para verificar se o banco de dados está online
      interval: 10s #Intervalo de tempo para verificar se o banco de dados está online
      timeout: 5s #Tempo máximo para verificar se o banco de dados está online
      retries: 5 #Número de vezes que o comando será executado
    restart: unless-stopped #Reinicia o serviço se ele cair

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:1234@db:5432/gateway?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  go-gateway-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: gateway
      DB_PORT: 5432
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres_data:

